/**
 * 12 character avatars for the AdkClaw cohort fleet.
 *
 * Categories: 4 boys, 4 girls with hijab, 4 girls without hijab.
 * Each character has a personality tag (studious / cool / friendly / creative).
 *
 * Rendering: painterly portraits in `public/avatars/<id>.png`, generated by
 * `scripts/generate-avatars.mjs` via Imagen 3 on Vertex AI. Re-run the script
 * to regenerate (cost: ~$0.04 per portrait).
 */

import type { AvatarPreset } from './types';

export type AvatarCategory = 'boys' | 'hijab' | 'no-hijab';
export type AvatarPersonality = 'studious' | 'cool' | 'friendly' | 'creative';

export interface AvatarCharacter {
  id: AvatarPreset;
  /** No longer displayed — kept for backwards compatibility with existing data. */
  name: string;
  category: AvatarCategory;
  personality: AvatarPersonality;
  /** Accent color for the ring + glow cue */
  accent: string;
  /** Soft-glow halo color (rgba) */
  glow: string;
}

const ACCENT = {
  blue: { accent: '#3B82F6', glow: 'rgba(59, 130, 246, 0.4)' },
  gold: { accent: '#facc15', glow: 'rgba(250, 204, 21, 0.4)' },
  emerald: { accent: '#10b981', glow: 'rgba(16, 185, 129, 0.35)' },
  coral: { accent: '#fb7185', glow: 'rgba(251, 113, 133, 0.35)' },
  cyan: { accent: '#22d3ee', glow: 'rgba(34, 211, 238, 0.35)' },
  amber: { accent: '#f59e0b', glow: 'rgba(245, 158, 11, 0.35)' },
  rose: { accent: '#f43f5e', glow: 'rgba(244, 63, 94, 0.35)' },
  indigo: { accent: '#6366f1', glow: 'rgba(99, 102, 241, 0.35)' },
  teal: { accent: '#14b8a6', glow: 'rgba(20, 184, 166, 0.35)' },
  violet: { accent: '#a78bfa', glow: 'rgba(167, 139, 250, 0.35)' },
  orange: { accent: '#f97316', glow: 'rgba(249, 115, 22, 0.35)' },
  sky: { accent: '#0ea5e9', glow: 'rgba(14, 165, 233, 0.35)' },
};

export const AVATAR_CHARACTERS: Record<AvatarPreset, AvatarCharacter> = {
  // ─── Boys (4) ─────────────────────────────────────────────────────────
  chrome: {
    id: 'chrome',
    name: 'chrome',
    category: 'boys',
    personality: 'studious',
    ...ACCENT.blue,
  },
  bronze: { id: 'bronze', name: 'bronze', category: 'boys', personality: 'cool', ...ACCENT.amber },
  slate: {
    id: 'slate',
    name: 'slate',
    category: 'boys',
    personality: 'friendly',
    ...ACCENT.emerald,
  },
  cosmic: {
    id: 'cosmic',
    name: 'cosmic',
    category: 'boys',
    personality: 'creative',
    ...ACCENT.indigo,
  },

  // ─── Girls with hijab (4) ─────────────────────────────────────────────
  forest: {
    id: 'forest',
    name: 'forest',
    category: 'hijab',
    personality: 'studious',
    ...ACCENT.teal,
  },
  arctic: { id: 'arctic', name: 'arctic', category: 'hijab', personality: 'cool', ...ACCENT.sky },
  mint: { id: 'mint', name: 'mint', category: 'hijab', personality: 'friendly', ...ACCENT.rose },
  lavender: {
    id: 'lavender',
    name: 'lavender',
    category: 'hijab',
    personality: 'creative',
    ...ACCENT.violet,
  },

  // ─── Girls without hijab (4) ──────────────────────────────────────────
  sky: { id: 'sky', name: 'sky', category: 'no-hijab', personality: 'studious', ...ACCENT.cyan },
  coral: { id: 'coral', name: 'coral', category: 'no-hijab', personality: 'cool', ...ACCENT.coral },
  gold: { id: 'gold', name: 'gold', category: 'no-hijab', personality: 'friendly', ...ACCENT.gold },
  sunset: {
    id: 'sunset',
    name: 'sunset',
    category: 'no-hijab',
    personality: 'creative',
    ...ACCENT.orange,
  },
};

export const AVATAR_LIST: AvatarCharacter[] = Object.values(AVATAR_CHARACTERS);

export const AVATAR_CATEGORIES: { id: AvatarCategory; label: string }[] = [
  { id: 'boys', label: 'Boys' },
  { id: 'hijab', label: 'Girls with hijab' },
  { id: 'no-hijab', label: 'Girls' },
];

/**
 * Backwards-compat alias for code that imported AVATAR_PALETTES.
 */
export const AVATAR_PALETTES = AVATAR_CHARACTERS;

/**
 * Path to a character's painterly portrait. Generated by
 * scripts/generate-avatars.mjs (Imagen 3 on Vertex AI).
 */
export function avatarUrl(character: AvatarCharacter): string {
  return `/avatars/${character.id}.png`;
}
