/**
 * 16 character avatars for the AdkClaw cohort fleet.
 *
 * Categories: 8 boys, 8 girls (with mixed looks — some hijab, some not).
 * Each character has a personality tag (studious / cool / friendly / creative).
 *
 * Rendering: painterly portraits in `public/avatars/<id>.png`, generated by
 * `scripts/generate-avatars.mjs` via Imagen 3 on Vertex AI.
 */

import type { AvatarPreset } from './types';

export type AvatarCategory = 'boys' | 'girls';
export type AvatarPersonality = 'studious' | 'cool' | 'friendly' | 'creative';

export interface AvatarCharacter {
  id: AvatarPreset;
  /** No longer displayed — kept for backwards compatibility with existing data. */
  name: string;
  category: AvatarCategory;
  personality: AvatarPersonality;
  /** Accent color for the ring + glow cue */
  accent: string;
  /** Soft-glow halo color (rgba) */
  glow: string;
}

const ACCENT = {
  blue: { accent: '#3B82F6', glow: 'rgba(59, 130, 246, 0.4)' },
  gold: { accent: '#facc15', glow: 'rgba(250, 204, 21, 0.4)' },
  emerald: { accent: '#10b981', glow: 'rgba(16, 185, 129, 0.35)' },
  coral: { accent: '#fb7185', glow: 'rgba(251, 113, 133, 0.35)' },
  cyan: { accent: '#22d3ee', glow: 'rgba(34, 211, 238, 0.35)' },
  amber: { accent: '#f59e0b', glow: 'rgba(245, 158, 11, 0.35)' },
  rose: { accent: '#f43f5e', glow: 'rgba(244, 63, 94, 0.35)' },
  indigo: { accent: '#6366f1', glow: 'rgba(99, 102, 241, 0.35)' },
  teal: { accent: '#14b8a6', glow: 'rgba(20, 184, 166, 0.35)' },
  violet: { accent: '#a78bfa', glow: 'rgba(167, 139, 250, 0.35)' },
  orange: { accent: '#f97316', glow: 'rgba(249, 115, 22, 0.35)' },
  sky: { accent: '#0ea5e9', glow: 'rgba(14, 165, 233, 0.35)' },
  slate: { accent: '#94a3b8', glow: 'rgba(148, 163, 184, 0.35)' },
  lime: { accent: '#84cc16', glow: 'rgba(132, 204, 22, 0.35)' },
  red: { accent: '#ef4444', glow: 'rgba(239, 68, 68, 0.35)' },
  fuchsia: { accent: '#d946ef', glow: 'rgba(217, 70, 239, 0.35)' },
};

export const AVATAR_CHARACTERS: Record<AvatarPreset, AvatarCharacter> = {
  // ─── Boys (8) ─────────────────────────────────────────────────────────
  chrome: {
    id: 'chrome',
    name: 'chrome',
    category: 'boys',
    personality: 'studious',
    ...ACCENT.blue,
  },
  nova: { id: 'nova', name: 'nova', category: 'boys', personality: 'studious', ...ACCENT.fuchsia },
  bronze: { id: 'bronze', name: 'bronze', category: 'boys', personality: 'cool', ...ACCENT.amber },
  onyx: { id: 'onyx', name: 'onyx', category: 'boys', personality: 'cool', ...ACCENT.slate },
  slate: {
    id: 'slate',
    name: 'slate',
    category: 'boys',
    personality: 'friendly',
    ...ACCENT.emerald,
  },
  pine: { id: 'pine', name: 'pine', category: 'boys', personality: 'friendly', ...ACCENT.lime },
  cosmic: {
    id: 'cosmic',
    name: 'cosmic',
    category: 'boys',
    personality: 'creative',
    ...ACCENT.indigo,
  },
  ember: { id: 'ember', name: 'ember', category: 'boys', personality: 'creative', ...ACCENT.red },

  // ─── Girls (8) — mix of looks, some with hijab, some without ──────────
  forest: {
    id: 'forest',
    name: 'forest',
    category: 'girls',
    personality: 'studious',
    ...ACCENT.teal,
  },
  sky: { id: 'sky', name: 'sky', category: 'girls', personality: 'studious', ...ACCENT.cyan },
  arctic: { id: 'arctic', name: 'arctic', category: 'girls', personality: 'cool', ...ACCENT.sky },
  coral: { id: 'coral', name: 'coral', category: 'girls', personality: 'cool', ...ACCENT.coral },
  mint: { id: 'mint', name: 'mint', category: 'girls', personality: 'friendly', ...ACCENT.rose },
  gold: { id: 'gold', name: 'gold', category: 'girls', personality: 'friendly', ...ACCENT.gold },
  lavender: {
    id: 'lavender',
    name: 'lavender',
    category: 'girls',
    personality: 'creative',
    ...ACCENT.violet,
  },
  sunset: {
    id: 'sunset',
    name: 'sunset',
    category: 'girls',
    personality: 'creative',
    ...ACCENT.orange,
  },
};

export const AVATAR_LIST: AvatarCharacter[] = Object.values(AVATAR_CHARACTERS);

export const AVATAR_CATEGORIES: { id: AvatarCategory; label: string }[] = [
  { id: 'boys', label: 'Boys' },
  { id: 'girls', label: 'Girls' },
];

/**
 * Backwards-compat alias for code that imported AVATAR_PALETTES.
 */
export const AVATAR_PALETTES = AVATAR_CHARACTERS;

/**
 * Path to a character's painterly portrait. Generated by
 * scripts/generate-avatars.mjs (Imagen 3 on Vertex AI).
 */
export function avatarUrl(character: AvatarCharacter): string {
  return `/avatars/${character.id}.png`;
}
